# config/secrets.yml
defaults: &defaults
  secret_key_base: '3be0afd491abe88809e6463a0c7e2c68a870a182a16667a1d7cc3657cf3129e0d2a9be301097678fc2521d85b446201001f7c9f1f06d70afd48a3872900718c1'
  devise_secret_key: 'ef7d29691e7ea51fd0439cb054cfa4926467f648b25ed49a569dc918d661dd8e1008dbf66f2ab18463046edfbb04573b633c5d3990ea3aecf8087c63bde725f2'
  devise_pepper: '4884116ac4787886fe6e235d8a21f47f365d500804bf29ef07f06a9ca7e120434e70170915452a70294f2f4f22b332c4286a9b2517fe8282937109a57c4336bc'
  email_addresses: &email_addresses
    support: Money Manage <jayshreeanandakumar@gmail.com>
  truelayer_client_id: <%= ENV['TRUELAYER_CLIENT_ID'] %>
  truelayer_client_secret: <%= ENV['TRUELAYER_CLIENT_SECRET'] %>
  currency_cloud_login_id: <%= ENV['CURRENCY_CLOUD_LOGIN_ID'] %>
  currency_cloud_api_key: <%= ENV['CURRENCY_CLOUD_API_KEY'] %>
  starling_client_id: <%= ENV['STARLING_CLIENT_ID'] %>
  starling_client_secret: <%= ENV['STARLING_CLIENT_SECRET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_region: <%= ENV['S3_REGION'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>

secured: &secured
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>

development:
  <<: *defaults
  root_url: 'http://localhost:3000'

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured
  root_url: 'https://money-manage-app.herokuapp.com'

